### PR TITLE
trim instead of drop long samples

### PR DESCRIPTION
**Pull request by aireenmei**
https://github.com/google/maxtext/issues/274

### CODE REVIEW

**Comment by rwitten** [comment]
Have you done convergence check here?

**Comment by aireenmei** [comment]
Done. Convergence looks ok, after 20400 steps, "Mean of last 10 losses is 2.481567859649658", log: "https://pantheon.corp.google.com/kubernetes/service/us-east5/v5e-256-bodaborg/default/aireen-v5e256-0119-0155/logs?e=13802955&mods=allow_workbench_image_override&project=tpu-prod-env-multipod"

(main commit convergence for comparison: https://pantheon.corp.google.com/kubernetes/service/us-east5/v5e-256-bodaborg/default/aireen-v5e256-0119-1202/logs?e=13802955&mods=allow_workbench_image_override&project=tpu-prod-env-multipod )

A separate note: I noticed in the convergence recipe, per_device_batch_size was increased from 2 to 8, which increased the step time, but took less steps to reach ~2.6. Should we decrease the 20400 steps for convergence test? Now it took ~4.5 h compared with ~2.2 h earlier this month

**Review by rwitten — APPROVED** [review]
Thanks for the CR!

Matt is thinking through the convergence test recipe, let's not worry about it right now.

**Comment by aireenmei** [comment]
I've stashed the commits and it should be ready to merge. Could you merge?

**Pull request merged**
