### PR TITLE
cudnn flash attention GQA support

### PR DESCRIPTION
**Pull request by kocchop**
1. Used new stable API for cudnn flash attention
2. It now has support for GQA

### CODE REVIEW

**Comment by kocchop** [comment]
@rwitten here is the PR for GQA support in Flash Attention. Please let me if you have any suggestions.

**Review by rwitten — APPROVED** [review]
Delegating to @yangyuwei for real approval

**Review by yangyuwei — APPROVED** [review]
Thanks for adding GQA support!

**Review by yangyuwei — APPROVED** [review]

**Comment by yangyuwei** [comment]
The code changes have been pushed to Github via this commit (https://github.com/google/maxtext/commit/f04ba7628843b5c35752f6e8c3b9929b8807b285) triggered by copybara. I'd close this PR. Thank you!

**Pull request closed without merging**
