### PR TITLE
Add support for installing nightly version of`tensorboard_plugin_profile`

### PR DESCRIPTION
**Pull request by yashs97**
Helpful for ensuring that a profile collected with nightlies work with `tbp-nightly`

### CODE REVIEW

**Comment by bvandermoon** [comment]
I'm generally ok with this change. But just wondering if there is a need for it? For example, is it helpful for your workflow? Is it true that JAX nightly users also want tbp-nightly?

**Review by bvandermoon — COMMENTED** [review]
I'm generally ok with this change. But just wondering if there is a need for it? For example, is it helpful for your workflow? Is it true that JAX nightly users also want tbp-nightly?

**Comment by shahyash10** [comment]
> I'm generally ok with this change. But just wondering if there is a need for it? For example, is it helpful for your workflow? Is it true that JAX nightly users also want tbp-nightly?

It is helpful for the nightly XLML tests and ensures that a profile collected with nightly version of JAX works with nightly version of `tbp`

**Comment by bvandermoon** [comment]
> > I'm generally ok with this change. But just wondering if there is a need for it? For example, is it helpful for your workflow? Is it true that JAX nightly users also want tbp-nightly?
> 
> It is helpful for the nightly XLML tests and ensures that a profile collected with nightly version of JAX works with nightly version of `tbp`

Got it, makes sense. Thanks Yash. Please add that to the description for context

**Review by bvandermoon — APPROVED** [review]

**Review by rwitten — CHANGES_REQUESTED** [review]
you should uninstall ahead of time like we do for Jax/Jaxlib. That way we can change.

**Review by rwitten — APPROVED** [review]

**Pull request merged**
