### PR TITLE
mixed precision configs with higher tokens/sample

### PR DESCRIPTION
**Pull request by singh-mitali**
Adding mixed precision configs which qualify tokens/sample constraint for mlperf.

### CODE REVIEW

**Review by vipannalla — APPROVED** [review]
I know you can't add a comment in json, but can you add a README in `maxtext/MaxText/configs/quantization/` with a sentence or two about each of the configs in that dir?

**Comment by mitalisi** [comment]
> I know you can't add a comment in json, but can you add a README in `maxtext/MaxText/configs/quantization/` with a sentence or two about each of the configs in that dir?

Sure. Will do this next week as part of b/352355780.

**Comment by gobbleturk** [comment]
> > I know you can't add a comment in json, but can you add a README in `maxtext/MaxText/configs/quantization/` with a sentence or two about each of the configs in that dir?
> 
> Sure. Will do this next week as part of b/352355780.

Can we do it in this PR? At the very least for the two files that this PR adds? I didn't realize json files don't support comments. You can add comments for the other json files like those added in https://github.com/google/maxtext/pull/762 in future PRs, but we should try to have PRs stay self contained

**Review by gobbleturk — CHANGES_REQUESTED** [review]
Can we add documentation for these as Vipan suggests?

**Comment by mitalisi** [comment]
Did not use this config

**Pull request closed without merging**
